name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./Frontend-v1-Original

jobs:
  unit_test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: ./Frontend-v1-Original/yarn.lock

      - run: yarn --frozen-lockfile
      - run: yarn test

  next_lint:
    name: Next Lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: ./Frontend-v1-Original/yarn.lock

      - run: yarn --frozen-lockfile
      - run: yarn lint

  tsc:
    name: Type Checking
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: ./Frontend-v1-Original/yarn.lock
      - run: yarn --frozen-lockfile
      - run: yarn tsc
